### PR TITLE
added ferox-config.toml to install formula

### PR DESCRIPTION
**Pull request by epi052**
Of note:
- i use `cp -n` to not overwrite an existing file, though I'm not sure if that's valid on a mac
- i use `mkdir -p` so there are no errors if the directory exists, though again, i'm not sure if this translates from linux to mac
- i use `/Users/USER/Library/Application Support/feroxbuster` based on [this library](https://docs.rs/dirs/3.0.1/dirs/fn.config_dir.html), I'm not sure if it exists by default or not

### CODE REVIEW

**Comment by epi052** [comment]
On second thought, for homebrew installs, we could dump the config in the same location as the binary itself.  It's one of the locations that feroxbuster will check.  

It probably makes more sense from an uninstall perspective and keeps everything in the homebrew-known location.

Maybe we could echo the location to stdout so folks know where it is?

**Comment by epi052** [comment]
On third thought, I think the banner will print the config location as long as it's found. I don't think it matters if any actual config values are found

**Comment by tgotwig** [comment]
I can test it on my Mac when you say me what to do 🧪🙂

**Comment by epi052** [comment]
Good deal. I'll test the changes on linux then update this PR to match.

**Comment by epi052** [comment]
Ok, it's ready for review. Config file should get placed inside the bin folder, then copied with `-n` to remove the `.example` suffix.  

The config location is in the banner after install. 

PS: I'm glad your bot is keeping my ruby nice and neat, that's pretty nice.

**Comment by tgotwig** [comment]
```fish
↪ ll /usr/local/bin | grep ferox
lrwxr-xr-x  1 tgotwig  admin    64B Oct 10 19:31 ferox-config.toml -> ../Cellar/feroxbuster/64-macos-feroxbuster/bin/ferox-config.toml
lrwxr-xr-x  1 tgotwig  admin    72B Oct 10 19:31 ferox-config.toml.example -> ../Cellar/feroxbuster/64-macos-feroxbuster/bin/ferox-config.toml.example
lrwxr-xr-x  1 tgotwig  admin    58B Oct 10 19:31 feroxbuster -> ../Cellar/feroxbuster/64-macos-feroxbuster/bin/feroxbuster
```

**Comment by epi052** [comment]
Thanks for testing! merging with new 1.0.4 url

**Pull request merged**
